service: bewgleassignment
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

  iam:
    role: arn:aws:iam::469433382165:role/csv_to_dynamodb

functions:
  csv_dump_to_dynamodb:
    handler: handler.csv_dump_to_dynamodb
    events:
      - s3:
          bucket: bewgle-csv-s3-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: data/
            - suffix: .csv
          existing: true
